# Header
menu:
  主页: /
  所有文章: /archives/
  #博客首页: /Resume/H1
  #前端页面: /works
  #前端导航: /FrontEndGuide/V1
  #品味摄影: /instagram
  # 随笔: /tags/随笔
  标签云: /tags/
  关于我: /about/

# SubNav
subnav:
  mail: "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=PAkNDgsKBQ4MCnxNTRJfU1E"
  github: "https://github.com/mazouri"
  zhihu: "https://www.zhihu.com/people/ma-zou-ri-le"
  weibo: "http://weibo.com/u/5621856557"
  #google: "#"
  #twitter: "#"
  #facebook: "#"
  rss: /atom.xml
  #linkedin: "https://www.linkedin.com/in/%E5%BF%A0%E6%88%90-%E6%9D%8E-a48562b1"
  #douban: "#"
  #google: "#"
  #zhihu: "zhihu"
  #douban: "douban"
  #Facebook: "#"
  #Google: "#"
  #Twitter: "#"
  #LinkedIn: "#"
  #QQ: "#"
  #微信: "Wechat"
  #PayPal: "#"
  #StackOverflow: "#"
  #Instagram: "#"
  #Flickr: "#"
  
  #fa-weibo: "http://weibo.com/lishangmou"
  #fa-github: 
  #fa-linkedin:
  #fa-Instagram:
  #fa-rss: 
  #fa-twitter:
  #fa-facebook:
  #fa-google:
  #fa-mail:
  #fa-stackoverflow:
  
# "5": show images form bg-1.jpg to bg-5.jpg in `/yelee/source/background/`
# "5": 显示`/yelee/source/background/`文件夹中 bg-1.jpg 到 bg-5.jpg 这5张图片
# "0": white-gray background | 淳朴灰白背景
# background_image: 1

# Content
excerpt_link: 阅读全文 #修改more>>的文字
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
#google_analytics: ''
baidu_analytics: true
favicon: /img/favicon.png

#你的头像url
avatar: "/img/head.jpg"

#是否开启分享
share: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key（http://duoshuo-key.duoshuo.com/）
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: mazouri

#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  Hexo: https://hexo.io
  GitHub: https://pages.github.com/
  MOxFIVE: http://moxfive.xyz/

swift_search:
  enable: true

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 纠棱厚，海贼控；爱代码，强迫症；常熬夜，闹酩掰；人生短，逛今宵。
